[phases.setup]
nixPkgs = ["python311", "postgresql", "rustc", "cargo", "gcc", "libffi", "openssl"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
